#!/usr/bin/env bash
#A bash script that prints Best School 10 with conditions

var=1
str="Best School"
while [[ $var -le 10 ]]
do
    if [[ $var -eq 9 ]]
    then
        echo "Hi"
    else
        echo $str
    fi
    (( var++ ))
done