#!/usr/bin/env bash
#Alx and Trouble be like 5 and 6, Dedicating this commit to My Journey in the Tech Field, devops na ur mate?

var=1
str="Best School"
while [[ $var -le 10 ]]
do
    if [[] $var -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $var -eq 8 ]]
    then
        echo "good luck"
    else
        echo $str
    fi
    (( var++ ))
done