#!/usr/bin/env bash
#check if a file exist

file="school"
if [ -e "$file" ]
then
	echo "${file} file exist"
	if [[ -s "$file" ]]
	then
		echo "${file} file not empty"
	elif [[ ! -s "$file" ]]
	then
		echo "${file} file exist"
	elif [[ -f "$file" ]]
	then
		echo "${file} file is a regular file"
	fi
else
	echo "${file} file does not exist"
fi
