#!/usr/bin/env bash
#check if a file exist

file="school"
if [[ -e "$file" ]]
then
	echo "school file exist"
	if [[ -s "$file" ]]
	then
		echo "school file not empty"
	elif [[ ! -s "$file" ]]
	then
		echo "school file exist"
	elif [[ -f "$file" ]]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
